;JagStudio Jag Pad Constants - Zero Player

AUDIOPLAYER::		DC.W		0

JAGPAD_UP::			DC.L		(1<<2)		// Up
JAGPAD_DOWN::		DC.L		(1<<3)		// Down
JAGPAD_LEFT::		DC.L		(1<<4)		// Left
JAGPAD_RIGHT::		DC.L		(1<<5)		// Right
JAGPAD_HASH::		DC.L		(1<<20)		// Hash (#)
JAGPAD_9::			DC.L		(1<<21)		// 9
JAGPAD_6::			DC.L		(1<<22)		// 6
JAGPAD_3::			DC.L		(1<<23)		// 3
JAGPAD_PAUSE::		DC.L		(1<<0)		// Pause
JAGPAD_A::			DC.L		(1<<1)		// A button
JAGPAD_OPTION::		DC.L		(1<<19)	 	// Option
JAGPAD_STAR::		DC.L		(1<<8)	 	// Star 
JAGPAD_7::			DC.L		(1<<9)	 	// 7
JAGPAD_4::			DC.L		(1<<10)	 	// 4
JAGPAD_1::			DC.L		(1<<11)	 	// 1
JAGPAD_0::			DC.L		(1<<14)	 	// 0 (zero)
JAGPAD_8::			DC.L		(1<<15)	 	// 8
JAGPAD_5::			DC.L		(1<<16)	 	// 5
JAGPAD_2::			DC.L		(1<<17)	 	// 2
JAGPAD_B::			DC.L		(1<<7)	 	// B button
JAGPAD_C::			DC.L		(1<<13)	  	// C button


;Pro controller helpers
JAGPAD_TL::			DC.L		(1<<10)		// Shoulder Left		(PAD 4)
JAGPAD_TR::			DC.L		(1<<22)		// Shoulder Right		(PAD 6)
JAGPAD_Z::			DC.L		(1<<9)	 	// Z					(PAD 7)
JAGPAD_Y::			DC.L		(1<<15)	 	// Y					(PAD 8)
JAGPAD_X::			DC.L		(1<<21)		// X					(PAD 9)


;Zero specific extra constants
JAGPAD_C1::			DC.L     ( 1 << 6 )
JAGPAD_C2::			DC.L     ( 1 << 12 )
JAGPAD_C3::			DC.L     ( 1 << 18 )     