;JagStudio Jag Pad Constants - LSP

AUDIOPLAYER::		DC.W		2

JAGPAD_UP::			DC.L		1				// Up
JAGPAD_DOWN::		DC.L		2				// Down
JAGPAD_LEFT::		DC.L		4				// Left
JAGPAD_RIGHT::		DC.L		8				// Right
JAGPAD_HASH::		DC.L		16				// Hash (#)
JAGPAD_9::			DC.L		32				// 9
JAGPAD_6::			DC.L		64				// 6
JAGPAD_3::			DC.L		128				// 3
JAGPAD_PAUSE::		DC.L		256				// Pause
JAGPAD_A::			DC.L		512				// A button
JAGPAD_OPTION::		DC.L		2048			// Option
JAGPAD_STAR::		DC.L		4096			// Star 
JAGPAD_7::			DC.L		8192			// 7
JAGPAD_4::			DC.L		16384			// 4
JAGPAD_1::			DC.L		32768			// 1
JAGPAD_0::			DC.L		65536			// 0 (zero)
JAGPAD_8::			DC.L		131072			// 8
JAGPAD_5::			DC.L		262144			// 5
JAGPAD_2::			DC.L		524288			// 2
JAGPAD_B::			DC.L		2097152			// B button
JAGPAD_C::			DC.L		33554432	  	// C button

;Pro controller helpers
JAGPAD_TL::			DC.L		16384			// Shoulder Left		(PAD 4)
JAGPAD_TR::			DC.L		64				// Shoulder Right		(PAD 6)
JAGPAD_Z::			DC.L		8192	 		// Z					(PAD 7)
JAGPAD_Y::			DC.L		131072	 		// Y					(PAD 8)
JAGPAD_X::			DC.L		32				// X					(PAD 9)