;;
;; RAPTOR-U235 Module
;;
;; (c) REBOOT
;;

			.extern		RAPTOR_mt_init
			.extern		RAPTOR_mt_load
			.extern		RAPTOR_mt_save
			.extern		RAPTOR_MTtrash
			.extern		raptor_mt_present

			.extern		raptor_MTwork
			.extern		raptor_mtapp
			.extern		raptor_mtfn
			.extern		raptor_MT_save_length
			.extern		raptor_MT_start_address
			.extern		raptor_MT_save_length
			
			

; END OF FILE			